# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:

  # - name: 主页
  #   url: home
  #   weight: 1

  # - name: Tour
  #   url: tour
  #   weight: 10

  - name: 研究团队
    url: people
    weight: 11
    lang: zh

  - name: Research Team
    url: people
    weight: 11
    lang: en

  - name: 团队愿景
    url: value
    weight: 12
    lang: zh

  - name: Team Vision
    url: value
    weight: 12
    lang: en

  - name: 研究简介
    url: research-introduction
    weight: 13
    lang: zh

  - name: Research Introduction
    url: research-introduction
    weight: 13
    lang: en

  # - name: News
  #   url: post
  #   weight: 20

  # - name: Events
  #   url: event
  #   weight: 40

  - name: 学术论文
    url: publication
    weight: 50
    lang: zh

  - name: Publications
    url: publication
    weight: 50
    lang: en

  - name: 科研项目
    url: projects
    weight: 51
    lang: zh

  - name: Projects
    url: projects
    weight: 51
    lang: en

  - name: 招生指南
    url: contact
    weight: 60
    lang: zh

  - name: Admission Guide
    url: contact
    weight: 60
    lang: en
